export default images={
    "0": require("../../assets/Images/bearProfil.png"),
    "1": require("../../assets/Images/bunnyProfil.png"),
    "2": require("../../assets/Images/catProfil.png"),
    "3": require("../../assets/Images/deerProfil.png"),
    "4": require("../../assets/Images/dogProfil.png"),
    "5": require("../../assets/Images/elephantProfil.png"),
    "6": require("../../assets/Images/giraffeProfil.png"),
    "7": require("../../assets/Images/henProfil.png"),
    "8": require("../../assets/Images/koalaProfil.png"),
    "9": require("../../assets/Images/lionProfil.png"),
    "10": require("../../assets/Images/monkeyProfil.png"),
    "11": require("../../assets/Images/owlProfil.png"),
    "12": require("../../assets/Images/pandaProfil.png"),
    "13": require("../../assets/Images/pigProfil.png"),
    "14": require("../../assets/Images/raccoonProfil.png"),
    "15": require("../../assets/Images/rhinoProfil.png"),
    "16": require("../../assets/Images/tigerProfil.png"),
    "17": require("../../assets/Images/zebraProfil.png"),
    "18": require("../../assets/Images/logo.png"),
}